name: SDK CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release-**'
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: lint check
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.8
          arguments: check

  unit:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.8
          arguments: test testDebugUnitTest

  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: build project
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.8
          arguments: build assembleDebug